name: Docs Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docbuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: linux.2xlarge
          # ideally we run on 3.8 and 3.9 as well, however we are limited in resources.
           python-version: 3.8
           python-tag: "py38"
    steps:
      - name: Checkout MultiPy
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          set -eux
          sudo yum makecache --refresh
          sudo yum install -y pandoc doxygen
          pip install -r docs/requirements.txt
      - name: Setup SSH (Click me for login details)
        uses: ./.github/actions/setup-ssh
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}
      - name: Doc Test
        run: |
          cd docs
          make doctest
      - name: Linkcheck
        run: |
          cd docs
          make linkcheck
      - name: Doc Build
        run: |
          cd docs
          make html

  docpush:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: linux.2xlarge
          # ideally we run on 3.8 and 3.9 as well, however we are limited in resources.
           python-version: 3.8
           python-tag: "py38"
    needs: docbuild
    # if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout MultiPy
        uses: actions/checkout@v2
      - name: Set Identity
        run: |
          set -ex
          git config --global user.email "runner@github.com"
          git config --global user.name "MultiPy CI Runner"
      - name: Setup SSH (Click me for login details)
        uses: ./.github/actions/setup-ssh
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: |
          set -eux
          sudo yum makecache --refresh
          sudo yum install -y pandoc doxygen
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Build
        run: |
          set -ex
          bash docs/doc_push.sh --dry-run
      - name: Push
        run: |
          set -ex
          cd /tmp/multipy_docs_tmp/multipy_gh_pages
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
